FROM qacompany/qendpoint

WORKDIR /app

COPY loadOfflineData .
RUN chmod +x loadOfflineData.sh

EXPOSE 1234
ENTRYPOINT ["/usr/bin/env"]

CMD ["/bin/sh", "-c", "./loadOfflineData.sh && java -jar -Xmx${MEM_SIZE} qendpoint.jar"]
